# Generated by Django 3.2.25 on 2026-01-11 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('platform', models.CharField(choices=[('general', 'General'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('cleaned', 'Cleaned'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('metadata_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, unique=True)),
                ('risky_metadata_keys', models.TextField(default='[]')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('category', models.CharField(choices=[('location', 'Location'), ('device', 'Device'), ('author', 'Author'), ('timestamp', 'Timestamp'), ('camera', 'Camera'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_removed', models.BooleanField(default=False)),
                ('file_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_entries', to='main.fileanalysis')),
            ],
        ),
        migrations.AddIndex(
            model_name='metadataentry',
            index=models.Index(fields=['file_analysis', 'category'], name='main_metada_file_an_85693b_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['-created_at'], name='main_filean_created_9258da_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['user', '-created_at'], name='main_filean_user_id_fae1b9_idx'),
        ),
    ]
