# Generated by Django 3.2.25 on 2026-01-14 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='original_files/')),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='cleaned_files/')),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('platform', models.CharField(choices=[('general', 'General'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('cleaned', 'Cleaned'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('metadata_count', models.IntegerField(default=0)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, unique=True)),
                ('risky_metadata_keys', models.TextField(default='[]')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('category', models.CharField(choices=[('location', 'Location'), ('device', 'Device'), ('software', 'Software'), ('camera', 'Camera'), ('personal', 'Personal'), ('temporal', 'Temporal'), ('other', 'Other')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_entries', to='main.fileanalysis')),
            ],
            options={
                'verbose_name_plural': 'Metadata entries',
                'ordering': ['-risk_level', 'category'],
            },
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['share_token'], name='main_filean_share_t_6c2924_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['created_at'], name='main_filean_created_06cb42_idx'),
        ),
    ]
