# Generated by Django 6.0.4 on 2026-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalysis',
            name='share_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
