# Generated by Django 6.0.4 on 2026-05-01 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureShare',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('max_downloads', models.IntegerField(default=0)),
                ('current_downloads', models.IntegerField(default=0)),
                ('is_one_time', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_shares', to='main.fileanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureShareAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('failed_auth', 'Failed Auth')], max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='main.secureshare')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
