# Generated by Django 6.0.4 on 2026-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fileanalysis_share_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalysis',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
