# Generated by Django 6.0.4 on 2026-05-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_secureshare_secureshareaccesslog'),
        ('main', '0003_fileanalysis_job_id'),
    ]

    operations = [
    ]
